# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c21cbe2fc877c280c0b7fdf4ffd0f40273e9f296c52ac3942dbd6c1edb1e75ad634452634bc64da912761a716bb8a3bde98454b6b7f6d7409604e1ec801dffd

test:
  secret_key_base: ce7ebb5c69a24304de4b29894c73c2358e827d055c403a7bec0d85f4aba2e2f663e2fe93ffa9793bc6733aca5a8b94d693823e17be047c4846a0aa9bc8d69055

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
